[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "attn-from-scratch"
version = "0.1.0"
description = "Transformer-based English-to-French translation model"
requires-python = ">=3.10"
dependencies = ["python-dotenv"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["backend*", "src*", "training*"]